### PR TITLE
Ensure setuptools, wheel, and pip is present when initializing environment when using `uv`

### PR DESCRIPTION
**Pull request by cccs-rs**
Related to: https://github.com/CybercentreCanada/Maco/issues/57

### CODE REVIEW

**Comment by seb-acsc** [comment]
Unfortunately, doesn't seem to help with a fresh tox and virtual environment. 
I'm on Ubuntu 22.04.4 LTS and seeing tests succeed on 3.8 & 3.9 but fail on 3.11 and 3.12 in tox.

**Comment by cccs-ml** [comment]
I can also replicate outside of tox.

Creating a new venv where setuptools and wheel are not pre-installed. Install pytest, requirements.txt and tests/requirements.txt. Run `python -m pytest`.

**Comment by cccs-ml** [comment]
@cccs-rs, seems this was passing tests due to something pre-installed on the old Ubuntu 20.04. Ubuntu 20.04 end of support is Apr 2025, so technically still in support but I think it's more appropriate to test on Ubuntu 22.04 now.

**Comment by cccs-rs** [comment]
Closing in favour of: https://github.com/CybercentreCanada/Maco/pull/65

**Pull request closed without merging**
